// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Exercice3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exercice3() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(1918, 1030));
    driver.findElement(By.id("itemc")).click();
    driver.findElement(By.linkText("Laptops")).click();
    driver.findElement(By.linkText("Monitors")).click();
    driver.findElement(By.id("itemc")).click();
    vars.put("productName", driver.findElement(By.linkText("Samsung galaxy s6")).getText());
    vars.put("price", driver.findElement(By.cssSelector(".col-lg-4:nth-child(1) h5")).getText());
    driver.findElement(By.linkText("Samsung galaxy s6")).click();
    assertThat(driver.findElement(By.cssSelector(".price-container")).getText(), is("vars.get(\"price\").toString() *includes tax"));
    assertThat(driver.findElement(By.cssSelector(".name")).getText(), is("vars.get(\"productName\").toString()"));
    driver.findElement(By.linkText("Add to cart")).click();
    assertThat(driver.switchTo().alert().getText(), is("Product added"));
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.cssSelector("#exampleModal .btn-secondary")).click();
    driver.findElement(By.linkText("About us")).click();
    driver.findElement(By.cssSelector("#videoModal .btn")).click();
    driver.findElement(By.id("cartur")).click();
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2)")).getText(), is("vars.get(\"productName\").toString()"));
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Hmayda");
    driver.findElement(By.id("country")).sendKeys("Tunisia");
    driver.findElement(By.id("city")).sendKeys("Tunis");
    driver.findElement(By.id("card")).sendKeys("123456");
    driver.findElement(By.id("month")).sendKeys("5");
    driver.findElement(By.id("year")).sendKeys("2001");
    vars.put("name", driver.findElement(By.id("name")).getAttribute("value"));
    vars.put("country", driver.findElement(By.id("country")).getAttribute("value"));
    vars.put("city", driver.findElement(By.id("city")).getAttribute("value"));
    vars.put("card", driver.findElement(By.id("card")).getAttribute("value"));
    vars.put("month", driver.findElement(By.id("month")).getAttribute("value"));
    vars.put("year", driver.findElement(By.id("year")).getAttribute("value"));
    driver.findElement(By.cssSelector("#orderModal .btn-primary")).click();
    vars.put("lead", driver.findElement(By.cssSelector(".lead")).getText());
    driver.findElement(By.cssSelector(".confirm")).click();
  }
}
