// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Exercice3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exercice3() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(1918, 1030));
    driver.findElement(By.id("itemc")).click();
    driver.findElement(By.linkText("Laptops")).click();
    driver.findElement(By.linkText("Sony vaio i5")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    assertThat(driver.switchTo().alert().getText(), is("Product added"));
    driver.findElement(By.id("cartur")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("hmayda");
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("country")).sendKeys("Tunisia");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Tunis");
    driver.findElement(By.id("card")).click();
    driver.findElement(By.id("card")).sendKeys("123456");
    driver.findElement(By.id("month")).click();
    driver.findElement(By.id("month")).sendKeys("5");
    driver.findElement(By.cssSelector("#orderModal form")).click();
    driver.findElement(By.id("year")).click();
    driver.findElement(By.id("year")).sendKeys("2001");
    driver.findElement(By.cssSelector("#orderModal .btn-primary")).click();
    driver.findElement(By.cssSelector(".confirm")).click();
    driver.findElement(By.linkText("About us")).click();
    driver.findElement(By.cssSelector("#videoModal .btn")).click();
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.cssSelector("#exampleModal .btn-secondary")).click();
  }
}
