// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Exercice2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exercice2() {
    driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html");
    driver.manage().window().setSize(new Dimension(1918, 1030));
    driver.findElement(By.id("num1")).click();
    driver.findElement(By.id("num1")).sendKeys("4");
    vars.put("num1", driver.findElement(By.id("num1")).getAttribute("value"));
    driver.findElement(By.id("num2")).click();
    driver.findElement(By.id("num2")).sendKeys("2");
    vars.put("num2", driver.findElement(By.id("num2")).getAttribute("value"));
    driver.findElement(By.id("operator")).click();
    {
      WebElement dropdown = driver.findElement(By.id("operator"));
      dropdown.findElement(By.xpath("//option[. = '+']")).click();
    }
    {
      String value = driver.findElement(By.id("operator")).getAttribute("value");
      assertThat(value, is("addition"));
    }
    driver.findElement(By.cssSelector("button")).click();
    vars.put("result", js.executeScript("return parseInt(document.getElementById(\'num1\').value) + parseInt(document.getElementById(\'num2\').value);"));
    assertThat(driver.findElement(By.id("result")).getText(), is("Résultat : vars.get(\"result\").toString()"));
    driver.findElement(By.id("operator")).click();
    {
      WebElement dropdown = driver.findElement(By.id("operator"));
      dropdown.findElement(By.xpath("//option[. = '-']")).click();
    }
    {
      String value = driver.findElement(By.id("operator")).getAttribute("value");
      assertThat(value, is("subtraction"));
    }
    driver.findElement(By.cssSelector("button")).click();
    {
      String value = driver.findElement(By.id("operator")).getAttribute("value");
      assertThat(value, is("subtraction"));
    }
    driver.findElement(By.id("operator")).click();
    {
      WebElement dropdown = driver.findElement(By.id("operator"));
      dropdown.findElement(By.xpath("//option[. = '*']")).click();
    }
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("operator")).click();
    {
      WebElement dropdown = driver.findElement(By.id("operator"));
      dropdown.findElement(By.xpath("//option[. = '/']")).click();
    }
    {
      String value = driver.findElement(By.id("operator")).getAttribute("value");
      assertThat(value, is("division"));
    }
    driver.findElement(By.cssSelector("button")).click();
    if ((Boolean) js.executeScript("return (document.getElementById(\'num2\').value === \'0\')")) {
      assertThat(driver.findElement(By.id("result")).getText(), is("Infinity"));
    }
    if ((Boolean) js.executeScript("return (document.getElementById(\'num2\').value !== \'0\')")) {
      vars.put("result", js.executeScript("return parseInt(document.getElementById(\'num1\').value) / parseInt(document.getElementById(\'num2\').value);"));
      assertThat(driver.findElement(By.id("result")).getText(), is("Résultat : vars.get(\"result\").toString()"));
    }
    driver.findElement(By.id("num2")).sendKeys("0");
    driver.findElement(By.cssSelector("button")).click();
    if ((Boolean) js.executeScript("return (document.getElementById(\'num2\').value === \'0\')")) {
      assertThat(driver.findElement(By.id("result")).getText(), is("Résultat : Infinity"));
    }
    if ((Boolean) js.executeScript("return (document.getElementById(\'num2\').value !== \'0\')")) {
      vars.put("result", js.executeScript("return parseInt(document.getElementById(\'num1\').value) / parseInt(document.getElementById(\'num2\').value);"));
      assertThat(driver.findElement(By.id("result")).getText(), is("Résultat : vars.get(\"result\").toString()"));
    }
  }
}
